<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);

        DB::table('food')->delete();
         
        DB::table('food')->insert(array(

        array('f_id'=>'1','type'=>'Master Chef appetizer & starter','name'=>'Fried Wonton','price'=>'130'),
        array('f_id'=>'2','type'=>'Master Chef appetizer & starter','name'=>'Fish chips','price'=>'120'),
        array('f_id'=>'3','type'=>'Master Chef appetizer & starter','name'=>'French Fry','price'=>'120'),
        array('f_id'=>'4','type'=>'Master Chef appetizer & starter','name'=>'Spice Potato','price'=>'120'),
        array('f_id'=>'5','type'=>'Master Chef appetizer & starter','name'=>'Special Wonton','price'=>'180'),
        array('f_id'=>'6','type'=>'Master Chef appetizer & starter','name'=>'Fried Chicken Wings','price'=>'200'),
        array('f_id'=>'7','type'=>'Master Chef appetizer & starter','name'=>'Vegetable Cutlet','price'=>'160'),
        array('f_id'=>'8','type'=>'Master Chef appetizer & starter','name'=>'Spring Rolls','price'=>'140'),

        array('f_id'=>'9','type'=>'Master Chef exclusive appetizer & starter','name'=>'Cutlet(beef/chicken)','price'=>'200'),
        array('f_id'=>'10','type'=>'Master Chef exclusive appetizer & starter','name'=>'Master Chef special fried boll plate(prawn/chicken)','price'=>'260'),
        array('f_id'=>'11','type'=>'Master Chef exclusive appetizer & starter','name'=>'Chicken drum sticks','price'=>'200'),
        array('f_id'=>'12','type'=>'Master Chef exclusive appetizer & starter','name'=>'Fish Cake(prawn/desi fish)','price'=>'250'),
        array('f_id'=>'13','type'=>'Master Chef exclusive appetizer & starter','name'=>'Master Chef special egg rolls(fish/chicken)','price'=>'280'),
        array('f_id'=>'14','type'=>'Master Chef exclusive appetizer & starter','name'=>'Master Chef special sesame(prawn/chicken)','price'=>'280'),
        array('f_id'=>'15','type'=>'Master Chef exclusive appetizer & starter','name'=>'Prawn/chicken on toast','price'=>'240'),
        array('f_id'=>'16','type'=>'Master Chef exclusive appetizer & starter','name'=>'Sze chuan wonton','price'=>'180'),
		
		array('f_id'=>'17','type'=>'Master Chef exclusive salad','name'=>'Chicken-cashew nut salad','price'=>'370'),
		array('f_id'=>'18','type'=>'Master Chef exclusive salad','name'=>'Chicken and prawn-cashew nut salad','price'=>'400'),
		array('f_id'=>'19','type'=>'Master Chef exclusive salad','name'=>'Lab gai','price'=>'300'),
		array('f_id'=>'20','type'=>'Master Chef exclusive salad','name'=>'Master Chef Special griled(beef/chicken) salad','price'=>'340'),
		array('f_id'=>'21','type'=>'Master Chef exclusive salad','name'=>'prawn salad','price'=>'370'),
		array('f_id'=>'22','type'=>'Master Chef exclusive salad','name'=>'Sze chuan chicken and prawn salad','price'=>'350'),
		
		array('f_id'=>'23','type'=>'Master Chef soup dishes','name'=>'Vegetable soup','price'=>'130'),
		array('f_id'=>'24','type'=>'Master Chef soup dishes','name'=>'Chicken clear soup','price'=>'130'),
		array('f_id'=>'25','type'=>'Master Chef soup dishes','name'=>'Chicken vegetable soup','price'=>'140'),
		array('f_id'=>'26','type'=>'Master Chef soup dishes','name'=>'Sweet corn soup','price'=>'150'),
		array('f_id'=>'27','type'=>'Master Chef soup dishes','name'=>'Chicken corn soup','price'=>'160'),
		array('f_id'=>'28','type'=>'Master Chef soup dishes','name'=>'Prawn corn soup','price'=>'200'),
		array('f_id'=>'29','type'=>'Master Chef soup dishes','name'=>'Special corn soup','price'=>'180'),
		array('f_id'=>'30','type'=>'Master Chef soup dishes','name'=>'Thai soup','price'=>'180'),
		array('f_id'=>'31','type'=>'Master Chef soup dishes','name'=>'Special Thai soup','price'=>'200'),
		array('f_id'=>'32','type'=>'Master Chef soup dishes','name'=>'Special mixed Thai vegetable soup','price'=>'200'),

		
		array('f_id'=>'33','type'=>'Master Chef exclusive soup dishes','name'=>'Jack soup','price'=>'250'),
		array('f_id'=>'34','type'=>'Master Chef exclusive soup dishes','name'=>'Special hot and sour soup','price'=>'250'),
		array('f_id'=>'35','type'=>'Master Chef exclusive soup dishes','name'=>'Special cocktail soup','price'=>'260'),
		array('f_id'=>'36','type'=>'Master Chef exclusive soup dishes','name'=>'Master Chef special soup','price'=>'300'),
		array('f_id'=>'37','type'=>'Master Chef exclusive soup dishes','name'=>'Thai hot and sour soup','price'=>'250'),
		array('f_id'=>'38','type'=>'Master Chef exclusive soup dishes','name'=>'Tam-yam goong soup','price'=>'300'),
		array('f_id'=>'39','type'=>'Master Chef exclusive soup dishes','name'=>'Sze chuan soup','price'=>'250'),
		array('f_id'=>'40','type'=>'Master Chef exclusive soup dishes','name'=>'Sze chuan Thai chili soup','price'=>'250'),

		
		array('f_id'=>'41','type'=>'Master Chef fried rice dishes','name'=>'Vegetable fried rice','price'=>'140'),
		array('f_id'=>'42','type'=>'Master Chef fried rice dishes','name'=>'Egg fried rice','price'=>'160'),
		array('f_id'=>'43','type'=>'Master Chef fried rice dishes','name'=>'Chicken fried rice','price'=>'180'),
		array('f_id'=>'44','type'=>'Master Chef fried rice dishes','name'=>'Beef fried rice','price'=>'190'),
		array('f_id'=>'45','type'=>'Master Chef fried rice dishes','name'=>'Prawn fried rice','price'=>'180'),
		array('f_id'=>'46','type'=>'Master Chef fried rice dishes','name'=>'Chicken/beef massala  rice','price'=>'200'),
		array('f_id'=>'47','type'=>'Master Chef fried rice dishes','name'=>'Prawn massala rice','price'=>'210'),
		array('f_id'=>'48','type'=>'Master Chef fried rice dishes','name'=>'Thai fried rice','price'=>'260'),
		array('f_id'=>'49','type'=>'Master Chef fried rice dishes','name'=>'Master Chef special fried rice','price'=>'270'),
		
		
		array('f_id'=>'50','type'=>'Master Chef Chinese chicken dishes','name'=>'Master Chef fried chicken','price'=>'280'),
		array('f_id'=>'51','type'=>'Master Chef Chinese chicken dishes','name'=>'Fried chicken with onion chili','price'=>'290'),
		array('f_id'=>'52','type'=>'Master Chef Chinese chicken dishes','name'=>'Chicken chili onion','price'=>'300'),
		array('f_id'=>'53','type'=>'Master Chef Chinese chicken dishes','name'=>'Chicken chili onion dry','price'=>'310'),
		array('f_id'=>'54','type'=>'Master Chef Chinese chicken dishes','name'=>'Slice chicken chili','price'=>'300'),
		array('f_id'=>'55','type'=>'Master Chef Chinese chicken dishes','name'=>'Chicken with garlic and chili','price'=>'300'),
		array('f_id'=>'56','type'=>'Master Chef Chinese chicken dishes','name'=>'Sweet and sour chicken ball','price'=>'300'),
		
		
		array('f_id'=>'57','type'=>'Master Chef exclusive-5','name'=>'Slice chicken with cashwe nut(spice)','price'=>'320'),
		array('f_id'=>'58','type'=>'Master Chef exclusive-5','name'=>'Master Chef massala chicken','price'=>'300'),
		array('f_id'=>'59','type'=>'Master Chef exclusive-5','name'=>'Master Chef lemon chicken','price'=>'300'),
		array('f_id'=>'60','type'=>'Master Chef exclusive-5','name'=>'Master Chef special chicken jal fry(curry)','price'=>'300'),
		array('f_id'=>'61','type'=>'Master Chef exclusive-5','name'=>'Master Chef chicken sizzling','price'=>'330'),


		array('f_id'=>'62','type'=>'Master Chef Chinese beef dishes','name'=>'Sweet and sour beef','price'=>'290'),
		array('f_id'=>'63','type'=>'Master Chef Chinese beef dishes','name'=>'Sweet and sour beef boll','price'=>'290'),
		array('f_id'=>'64','type'=>'Master Chef Chinese beef dishes','name'=>'Hot and sour beef','price'=>'290'),
		array('f_id'=>'65','type'=>'Master Chef Chinese beef dishes','name'=>'Slice of beef with vegetable','price'=>'170'),
		array('f_id'=>'66','type'=>'Master Chef Chinese beef dishes','name'=>'Slice of beef with mushroom and vegetable','price'=>'220'),
		array('f_id'=>'67','type'=>'Master Chef Chinese beef dishes','name'=>'Beef chili onion','price'=>'290'),
		array('f_id'=>'68','type'=>'Master Chef Chinese beef dishes','name'=>'Beef chili dry','price'=>'290'),
		array('f_id'=>'69','type'=>'Master Chef Chinese beef dishes','name'=>'Beef chili gravy','price'=>'290'),

		array('f_id'=>'70','type'=>'Master Chef exclusive-2','name'=>'Master Chef special beef massala','price'=>'310'),
		array('f_id'=>'71','type'=>'Master Chef exclusive-2','name'=>'Master Chef special beef sizzling','price'=>'350'),

		array('f_id'=>'72','type'=>'Master Chef exclusive Chinese mutton dishes','name'=>'Mutton green chili onion','price'=>'330'),
		array('f_id'=>'73','type'=>'Master Chef exclusive Chinese mutton dishes','name'=>'Mutton chili gravy','price'=>'330'),
		array('f_id'=>'74','type'=>'Master Chef exclusive Chinese mutton dishes','name'=>'Mutton chili dry','price'=>'330'),
		array('f_id'=>'75','type'=>'Master Chef exclusive Chinese mutton dishes','name'=>'Mutton sizzling','price'=>'400'),

		array('f_id'=>'76','type'=>'Master Chef Chinese prawn dishes','name'=>'Sweet and sour prawn','price'=>'310'),
		array('f_id'=>'77','type'=>'Master Chef Chinese prawn dishes','name'=>'Sweet and sour prawn ball','price'=>'320'),
		array('f_id'=>'78','type'=>'Master Chef Chinese prawn dishes','name'=>'Hot sauce prawn','price'=>'310'),
		array('f_id'=>'79','type'=>'Master Chef Chinese prawn dishes','name'=>'Prawn with garlic sauce','price'=>'310'),
		array('f_id'=>'80','type'=>'Master Chef Chinese prawn dishes','name'=>'Prawn chili dry','price'=>'310'),
		array('f_id'=>'81','type'=>'Master Chef Chinese prawn dishes','name'=>'Prawn with onion and chili','price'=>'310'),
		array('f_id'=>'82','type'=>'Master Chef Chinese prawn dishes','name'=>'Prawn with mushroom ginger','price'=>'310'),
		array('f_id'=>'83','type'=>'Master Chef Chinese prawn dishes','name'=>'prawn with vegetable','price'=>'260'),

		array('f_id'=>'84','type'=>'Master Chef exclusive-4','name'=>'Master Chef special king prawn','price'=>'360'),
		array('f_id'=>'85','type'=>'Master Chef exclusive-4','name'=>'Prawn with basil leaf gravy','price'=>'320'),
		array('f_id'=>'86','type'=>'Master Chef exclusive-4','name'=>'China prawn','price'=>'380'),
		array('f_id'=>'87','type'=>'Master Chef exclusive-4','name'=>'Prawn sizzlings','price'=>'400'),

		
		array('f_id'=>'88','type'=>'Master Chef Chinese fish dishes','name'=>'Slice fish with vegetable','price'=>'220'),
		array('f_id'=>'89','type'=>'Master Chef Chinese fish dishes','name'=>'Hot sauce fish','price'=>'350'),
		array('f_id'=>'90','type'=>'Master Chef Chinese fish dishes','name'=>'Sweet and sour fish','price'=>'350'),
		array('f_id'=>'91','type'=>'Master Chef Chinese fish dishes','name'=>'Fish chili dry','price'=>'350'),
		array('f_id'=>'92','type'=>'Master Chef Chinese fish dishes','name'=>'Fish with ginger and mushroom','price'=>'350'),

		
		array('f_id'=>'93','type'=>'Master Chef exclusive-6','name'=>'Pomfret fried(Seasonal)','price'=>'360'),
		array('f_id'=>'94','type'=>'Master Chef exclusive-6','name'=>'Stream pomfret(Seasonal)','price'=>'360'),
		array('f_id'=>'95','type'=>'Master Chef exclusive-6','name'=>'Sweet and sour pomfret(Seasonal)','price'=>'370'),
		array('f_id'=>'96','type'=>'Master Chef exclusive-6','name'=>'Pomfret with garlic sauce(Seasonal)','price'=>'360'),
		array('f_id'=>'97','type'=>'Master Chef exclusive-6','name'=>'Sweet and sour red snapper(Seasonal)','price'=>'430'),
		array('f_id'=>'98','type'=>'Master Chef exclusive-6','name'=>'Master Chef special red snapper(Seasonal)','price'=>'450'),

		array('f_id'=>'99','type'=>'Master Chef chowmein/noodles dishes','name'=>'Vegetable chowmein','price'=>'230'),
		array('f_id'=>'100','type'=>'Master Chef chowmein/noodles dishes','name'=>'Chowmein with(chicken/prawn/beef/mutton)','price'=>'260'),
		array('f_id'=>'101','type'=>'Master Chef chowmein/noodles dishes','name'=>'Master Chef special chowmein','price'=>'300'),

		array('f_id'=>'102','type'=>'Master Chef chopsuey dishes','name'=>'Mixed vegetable chopsuey','price'=>'230'),
		array('f_id'=>'103','type'=>'Master Chef chopsuey dishes','name'=>'Chopsuey with(chicken/prawn/beef/mutton)','price'=>'270'),
		array('f_id'=>'104','type'=>'Master Chef chopsuey dishes','name'=>'American chopseuy','price'=>'280'),
		array('f_id'=>'105','type'=>'Master Chef chopsuey dishes','name'=>'Chinese chopsuey','price'=>'260'),
		array('f_id'=>'106','type'=>'Master Chef chopsuey dishes','name'=>'Master Chef special chopsuey','price'=>'300'),

		array('f_id'=>'107','type'=>'Master Chef Chinese vegetable dishes','name'=>'Plain vegetable','price'=>'150'),
		array('f_id'=>'108','type'=>'Master Chef Chinese vegetable dishes','name'=>'Steam vegetable','price'=>'150'),
		array('f_id'=>'109','type'=>'Master Chef Chinese vegetable dishes','name'=>'Mixed vegetable with(chicken/prawn/beef/mutton)','price'=>'150'),
		array('f_id'=>'110','type'=>'Master Chef Chinese vegetable dishes','name'=>'Mixed vegetable with oyster sauce','price'=>'150'),
		array('f_id'=>'111','type'=>'Master Chef Chinese vegetable dishes','name'=>'Master Chef special mixed vegetable','price'=>'230'),
				
		array('f_id'=>'112','type'=>'Master Chef Thai dishes','name'=>'Thai fried rice','price'=>'250'),
		array('f_id'=>'113','type'=>'Master Chef Thai dishes','name'=>'Thai vegetable with prawn,chicken,mushroom and chili','price'=>'250'),
		array('f_id'=>'114','type'=>'Master Chef Thai dishes','name'=>'Thai mushroom vegetable','price'=>'320'),
		array('f_id'=>'115','type'=>'Master Chef Thai dishes','name'=>'Thai mixed vegetable with oyster sauce','price'=>'300'),
		array('f_id'=>'116','type'=>'Master Chef Thai dishes','name'=>'Thai fried chicken','price'=>'350'),
		array('f_id'=>'117','type'=>'Master Chef Thai dishes','name'=>'Thai massala chicken','price'=>'300'),
		array('f_id'=>'118','type'=>'Master Chef Thai dishes','name'=>'Thai boneless chicken','price'=>'310'),
		array('f_id'=>'119','type'=>'Master Chef Thai dishes','name'=>'Thai boneless massala chicken','price'=>'310'),
		array('f_id'=>'120','type'=>'Master Chef Thai dishes','name'=>'Thai red curry with(chicken/prawn/beef/mutton)','price'=>'300'),
		array('f_id'=>'121','type'=>'Master Chef Thai dishes','name'=>'Thai beef chili dry','price'=>'300'),
		array('f_id'=>'122','type'=>'Master Chef Thai dishes','name'=>'Thai mutton chili dry','price'=>'300'),
		array('f_id'=>'123','type'=>'Master Chef Thai dishes','name'=>'Bangkok style vegetable','price'=>'280'),

		array('f_id'=>'124','type'=>'Master Chef exclusive-7','name'=>'Bangkok style fried chicken','price'=>'300'),
		array('f_id'=>'125','type'=>'Master Chef exclusive-7','name'=>'Thai sizzling with(chicken/prawn/beef/mutton) ','price'=>'370'),
		array('f_id'=>'126','type'=>'Master Chef exclusive-7','name'=>'Bangkok style sizzling with(chicken/prawn/beef/mutton)','price'=>'380'),
		array('f_id'=>'127','type'=>'Master Chef exclusive-7','name'=>'Shanghai style sizzling with(chicken/prawn/beef/mutton)','price'=>'380'),
		array('f_id'=>'128','type'=>'Master Chef exclusive-7','name'=>'Prawn with garlic and soya sauce','price'=>'380'),
		array('f_id'=>'129','type'=>'Master Chef exclusive-7','name'=>'Fried king prawn with garlic sauce','price'=>'440'),
		array('f_id'=>'130','type'=>'Master Chef exclusive-7','name'=>'Duck(massala/paprika)','price'=>'450'),
				
		array('f_id'=>'131','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan fried rice','price'=>'240'),
		array('f_id'=>'132','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan vegetable with chicken','price'=>'200'),
		array('f_id'=>'133','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan fried Chicken','price'=>'300'),
		array('f_id'=>'134','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan fish chili dry','price'=>'250'),
		array('f_id'=>'135','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan prawn chili dry','price'=>'280'),
		array('f_id'=>'136','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan beef chili dry','price'=>'300'),
		array('f_id'=>'137','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan mutton chili dry','price'=>'310'),
		array('f_id'=>'138','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan beef with ginger and white pepper','price'=>'240'),
		array('f_id'=>'139','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan fish chili gravy','price'=>'280'),
		array('f_id'=>'140','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan prawn chili gravy','price'=>'275'),
		array('f_id'=>'141','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan beef chili gravy','price'=>'280'),
		array('f_id'=>'142','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan mutton chili gravy','price'=>'290'),
		array('f_id'=>'143','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan slice chicken gravy','price'=>'260'),
		array('f_id'=>'144','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan boneless chicken','price'=>'280'),
		array('f_id'=>'145','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan mushroom gravy with(chicken/beef)','price'=>'300'),
		array('f_id'=>'146','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan mutton with mushroom gravy','price'=>'310'),
		array('f_id'=>'147','type'=>'Master Chef sze-chuan dishes','name'=>'Sze-chuan prawn with mushroom gravy','price'=>'320'),
		
		array('f_id'=>'148','type'=>'Master Chef exclusive-3','name'=>'Sze-chuan full chicken','price'=>'350'),
		array('f_id'=>'149','type'=>'Master Chef exclusive-3','name'=>'Sze-chuan duck with lemon sauce','price'=>'433'),
		array('f_id'=>'150','type'=>'Master Chef exclusive-3','name'=>'Sze-chuan lobster','price'=>'530'),
		
		array('f_id'=>'151','type'=>'Master Chef Indian Appetizer & starter dishes','name'=>'Vegetable pakora','price'=>'140'),
		array('f_id'=>'152','type'=>'Master Chef Indian Appetizer & starter dishes','name'=>'Chicken pakora','price'=>'180'),
		array('f_id'=>'153','type'=>'Master Chef Indian Appetizer & starter dishes','name'=>'Prawn or poneer pakora','price'=>'160'),
		array('f_id'=>'154','type'=>'Master Chef Indian Appetizer & starter dishes','name'=>'Raita salad','price'=>'140'),
		array('f_id'=>'155','type'=>'Master Chef Indian Appetizer & starter dishes','name'=>'Mixed salad','price'=>'100'),
		
		array('f_id'=>'156','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Plain polau','price'=>'160'),
		array('f_id'=>'157','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Vegetable polau','price'=>'180'),
		array('f_id'=>'158','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Motor polau','price'=>'200'),
		array('f_id'=>'159','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Jira polau','price'=>'180'),
		array('f_id'=>'160','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Kashmiri polau','price'=>'220'),
		array('f_id'=>'161','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Haidarabadi biriany with chicken','price'=>'360'),
		array('f_id'=>'162','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Haidarabadi biriany with desi sauce','price'=>'360'),
		array('f_id'=>'163','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Haidarabadi biriany with prawn','price'=>'370'),
		array('f_id'=>'164','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Dum Biriany(chicken/mutton)','price'=>'370'),
		array('f_id'=>'165','type'=>'Master Chef Indian polau & biriany dishes','name'=>'Special biriany','price'=>'400'),
		
		array('f_id'=>'166','type'=>'Nan roti','name'=>'Plain Nun','price'=>'40'),
		array('f_id'=>'167','type'=>'Nan roti','name'=>'Butter Nan','price'=>'45'),
		array('f_id'=>'168','type'=>'Nan roti','name'=>'Garlic Nan','price'=>'45'),
		array('f_id'=>'169','type'=>'Nan roti','name'=>'Kashmiri Nan','price'=>'60'),
		array('f_id'=>'170','type'=>'Nan roti','name'=>'Special Nan','price'=>'70'),
		
		array('f_id'=>'171','type'=>'Indian vegetable dishes','name'=>'Achari Aloo','price'=>'200'),
		array('f_id'=>'172','type'=>'Indian vegetable dishes','name'=>'Shobji(joypuri/milijhili/kalapuri)','price'=>'180'),
		array('f_id'=>'173','type'=>'Indian vegetable dishes','name'=>'Palok ponner','price'=>'200'),
		array('f_id'=>'174','type'=>'Indian vegetable dishes','name'=>'Motar ponner','price'=>'199'),
		array('f_id'=>'175','type'=>'Indian vegetable dishes','name'=>'Ponner makhani','price'=>'220'),
		array('f_id'=>'176','type'=>'Indian vegetable dishes','name'=>'Tondoori vegetable','price'=>'200'),
		array('f_id'=>'177','type'=>'Indian vegetable dishes','name'=>'Vegetable jhal fry','price'=>'180'),
		array('f_id'=>'178','type'=>'Indian vegetable dishes','name'=>'Dal butter fry','price'=>'150'),
		array('f_id'=>'179','type'=>'Indian vegetable dishes','name'=>'Tarka dal','price'=>'140'),
		array('f_id'=>'180','type'=>'Indian vegetable dishes','name'=>'Dal makhani','price'=>'180'),

		array('f_id'=>'181','type'=>'Indian chicken dishes','name'=>'Achari chicken','price'=>'320'),
		array('f_id'=>'182','type'=>'Indian chicken dishes','name'=>'Butter chicken','price'=>'300'),
		array('f_id'=>'183','type'=>'Indian chicken dishes','name'=>'Chicken tikka massala','price'=>'300'),
		array('f_id'=>'184','type'=>'Indian chicken dishes','name'=>'Chicken jhal fry','price'=>'300'),
		array('f_id'=>'185','type'=>'Indian chicken dishes','name'=>'Chicken dopiaza','price'=>'300'),
		array('f_id'=>'186','type'=>'Indian chicken dishes','name'=>'Chicken bhuna','price'=>'300'),
		array('f_id'=>'187','type'=>'Indian chicken dishes','name'=>'Chicken roast','price'=>'300'),
		array('f_id'=>'188','type'=>'Indian chicken dishes','name'=>'Chicken korma','price'=>'300'),
		array('f_id'=>'189','type'=>'Indian chicken dishes','name'=>'Karai chicken','price'=>'320'),
		array('f_id'=>'190','type'=>'Indian chicken dishes','name'=>'Resmi tikka massala','price'=>'300'),
	
		array('f_id'=>'191','type'=>'Indian beef dishes','name'=>'Beef achari','price'=>'310'),
		array('f_id'=>'192','type'=>'Indian beef dishes','name'=>'Beef bhuna','price'=>'300'),
		array('f_id'=>'193','type'=>'Indian beef dishes','name'=>'Beef karai','price'=>'300'),
		array('f_id'=>'194','type'=>'Indian beef dishes','name'=>'Beef massala','price'=>'300'),
		array('f_id'=>'195','type'=>'Indian beef dishes','name'=>'Beef jhal fry','price'=>'300'),

		array('f_id'=>'196','type'=>'Indian mutton dishes','name'=>'Mutton(achari/bhuna/massala)','price'=>'320'),
		array('f_id'=>'197','type'=>'Indian mutton dishes','name'=>'Mutton hundi','price'=>'310'),
		array('f_id'=>'198','type'=>'Indian mutton dishes','name'=>'Mutton karai','price'=>'310'),
		array('f_id'=>'199','type'=>'Indian mutton dishes','name'=>'Mutton korma','price'=>'310'),
		array('f_id'=>'200','type'=>'Indian mutton dishes','name'=>'Mutton roganjosh','price'=>'310'),

		array('f_id'=>'201','type'=>'Master Chef Indian prawn dishes','name'=>'Prawn dopiaza','price'=>'300'),
		array('f_id'=>'202','type'=>'Master Chef Indian prawn dishes','name'=>'Prawn malai curry','price'=>'300'),
		array('f_id'=>'203','type'=>'Master Chef Indian prawn dishes','name'=>'Prawn butter massala','price'=>'300'),
		array('f_id'=>'204','type'=>'Master Chef Indian prawn dishes','name'=>'Prawn karai','price'=>'300'),
		array('f_id'=>'205','type'=>'Master Chef Indian prawn dishes','name'=>'Tiger prawn(bhana/massala)','price'=>'300'),

		array('f_id'=>'206','type'=>'Master Chef Indian fish dishes','name'=>'Fish (butter/tikka) massala','price'=>'300'),
		array('f_id'=>'207','type'=>'Master Chef Indian fish dishes','name'=>'Fish karai','price'=>'300'),
		array('f_id'=>'208','type'=>'Master Chef Indian fish dishes','name'=>'Pomfret(bhana/fry/massala)','price'=>'370'),
		array('f_id'=>'209','type'=>'Master Chef Indian fish dishes','name'=>'Red snapper(bhana/fry/massala)','price'=>'480'),
		array('f_id'=>'210','type'=>'Master Chef Indian fish dishes','name'=>'Vetki(boneless) massala or dopiaza','price'=>'330'),

		array('f_id'=>'211','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Fish tikka kebab','price'=>'300'),
		array('f_id'=>'212','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Resmi kebab','price'=>'280'),
		array('f_id'=>'213','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Tengri kebab','price'=>'370'),
		array('f_id'=>'214','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Beef botti kebab','price'=>'300'),
		array('f_id'=>'215','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Mutton botti kebab','price'=>'300'),
		array('f_id'=>'216','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Chicken tondoori(1/2)','price'=>'200'),
		array('f_id'=>'217','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Full chicken tondoori','price'=>'400'),
		array('f_id'=>'218','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Prawn tondoori','price'=>'400'),
		array('f_id'=>'219','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Pomfret tondoori','price'=>'380'),
		array('f_id'=>'220','type'=>'Master Chef Indian dishes from tondoori oven','name'=>'Beef stack tondoori','price'=>'340'),
		
		array('f_id'=>'221','type'=>'Master Chef Bangla dishes','name'=>'Plain rice(as much as you can)','price'=>'30'),
		array('f_id'=>'222','type'=>'Master Chef Bangla dishes','name'=>'Stream rice(minimum for 3 pax)','price'=>'40'),
		array('f_id'=>'223','type'=>'Master Chef Bangla dishes','name'=>'Seasonal vegetable(Bangladesh style)','price'=>'25'),
		array('f_id'=>'224','type'=>'Master Chef Bangla dishes','name'=>'Dal','price'=>'30'),
		array('f_id'=>'225','type'=>'Master Chef Bangla dishes','name'=>'Thick dal','price'=>'35'),
		array('f_id'=>'226','type'=>'Master Chef Bangla dishes','name'=>'Murigonto','price'=>'35'),
		array('f_id'=>'227','type'=>'Master Chef Bangla dishes','name'=>'Aloo vorta','price'=>'15'),
		array('f_id'=>'228','type'=>'Master Chef Bangla dishes','name'=>'Shtki vorta','price'=>'40'),
		array('f_id'=>'229','type'=>'Master Chef Bangla dishes','name'=>'Prawn vorta','price'=>'45'),
		array('f_id'=>'230','type'=>'Master Chef Bangla dishes','name'=>'Taki vorta','price'=>'40'),
		array('f_id'=>'231','type'=>'Master Chef Bangla dishes','name'=>'Potol/tomato vorta(seasonal)','price'=>'35'),
		array('f_id'=>'232','type'=>'Master Chef Bangla dishes','name'=>'Beef bhuna','price'=>'100'),
		array('f_id'=>'233','type'=>'Master Chef Bangla dishes','name'=>'Mutton bhuna','price'=>'120'),
		array('f_id'=>'234','type'=>'Master Chef Bangla dishes','name'=>'Chicken bhuna','price'=>'100'),
		array('f_id'=>'235','type'=>'Master Chef Bangla dishes','name'=>'Fish(rui/katol)','price'=>'100'),
		array('f_id'=>'236','type'=>'Master Chef Bangla dishes','name'=>'Sutki curry','price'=>'100'),
		array('f_id'=>'237','type'=>'Master Chef Bangla dishes','name'=>'Koi fish','price'=>'140'),
		array('f_id'=>'238','type'=>'Master Chef Bangla dishes','name'=>'Hilsha fish','price'=>'150'),
		array('f_id'=>'239','type'=>'Master Chef Bangla dishes','name'=>'Small fish','price'=>'70'),
		array('f_id'=>'240','type'=>'Master Chef Bangla dishes','name'=>'Salad','price'=>'20'),
		
		array('f_id'=>'241','type'=>'Master Chef Fast food/Snacks','name'=>'Chicken roll','price'=>'35'),
		array('f_id'=>'242','type'=>'Master Chef Fast food/Snacks','name'=>'Vegetable roll','price'=>'30'),
		array('f_id'=>'243','type'=>'Master Chef Fast food/Snacks','name'=>'Fried chicken burger','price'=>'75'),
		array('f_id'=>'244','type'=>'Master Chef Fast food/Snacks','name'=>'Chicken burger','price'=>'50'),
		array('f_id'=>'245','type'=>'Master Chef Fast food/Snacks','name'=>'Chicken & cheese burger','price'=>'55'),
		array('f_id'=>'246','type'=>'Master Chef Fast food/Snacks','name'=>'Chicken bon','price'=>'40'),
		array('f_id'=>'247','type'=>'Master Chef Fast food/Snacks','name'=>'Hot dog','price'=>'40'),
		array('f_id'=>'248','type'=>'Master Chef Fast food/Snacks','name'=>'Toasted chicken sandwich','price'=>'35'),
		array('f_id'=>'249','type'=>'Master Chef Fast food/Snacks','name'=>'Toasted chicken & cheese sandwich','price'=>'45'),
		array('f_id'=>'250','type'=>'Master Chef Fast food/Snacks','name'=>'Club sandwich','price'=>'50'),
		
		array('f_id'=>'251','type'=>'Master Chef Desert','name'=>'Ice-cream(2 scoop)','price'=>'50'),
		array('f_id'=>'252','type'=>'Master Chef Desert','name'=>'Fessh food salad with ice-cream','price'=>'80'),
		array('f_id'=>'253','type'=>'Master Chef Desert','name'=>'Banana split','price'=>'50'),
		array('f_id'=>'254','type'=>'Master Chef Desert','name'=>'Fresh fruit platter','price'=>'50'),
		array('f_id'=>'255','type'=>'Master Chef Desert','name'=>'Egg pudding','price'=>'50'),

		array('f_id'=>'256','type'=>'Master Chef Beverage','name'=>'Mineral water(500ml)','price'=>'20'),
		array('f_id'=>'257','type'=>'Master Chef Beverage','name'=>'Mineral water(1.5liter)','price'=>'30'),
		array('f_id'=>'258','type'=>'Master Chef Beverage','name'=>'Soft drink(per glass)','price'=>'20'),
		array('f_id'=>'259','type'=>'Master Chef Beverage','name'=>'Soft drink(can)','price'=>'45'),
		array('f_id'=>'260','type'=>'Master Chef Beverage','name'=>'Energy drink(Speed)','price'=>'40'),
		array('f_id'=>'261','type'=>'Master Chef Beverage','name'=>'Fruit juice','price'=>'30'),
		array('f_id'=>'262','type'=>'Master Chef Beverage','name'=>'Fruit punch','price'=>'50'),
		array('f_id'=>'263','type'=>'Master Chef Beverage','name'=>'Fresh fruit juice(orange/apple/mango/papaya)','price'=>'60'),
		array('f_id'=>'264','type'=>'Master Chef Beverage','name'=>'Milk shake(vanilla/chocolate/stoaberry)','price'=>'50'),
		array('f_id'=>'265','type'=>'Master Chef Beverage','name'=>'Siberian brazes','price'=>'60'),
		array('f_id'=>'266','type'=>'Master Chef Beverage','name'=>'Special lassi','price'=>'50'),
		array('f_id'=>'267','type'=>'Master Chef Beverage','name'=>'Tea(milk tea/ice tea/leamon tea)','price'=>'20'),
		array('f_id'=>'268','type'=>'Master Chef Beverage','name'=>'Coffee(milk coffee/cold coffee)','price'=>'50'),
		array('f_id'=>'269','type'=>'Master Chef Beverage','name'=>'Black coffee','price'=>'50'),
		array('f_id'=>'270','type'=>'Master Chef Beverage','name'=>'Black frappe','price'=>'50'),

        //array('f_id'=>'','type'=>'','name'=>'','price'=>''),	
          ));
       }
 
}